### ISSUE TITLE
Message from author of Bearded Icons and Bearded Theme.

### ISSUE THREAD

**Issue by BeardedBear** [hunqng/openspace-icons#7]
Hello

I see that you are using my Bearded Icons extension to create your own icon pack, in your name. It would be appreciated if you notify at least in your readme that the base comes from me, otherwise it is like stealing.

PS: Same thing for your theme.

**Comment by hunqng** [comment]
Fixed!

**Comment by BeardedBear** [comment]
Thanks :)
